version: 2.1
orbs:
  node: circleci/node@4.1
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
workflows:
  build-deploy:
    jobs:
        - run:
            name: Front-End Install
            command: |
              npm run frontend:install
        - run:
            name: Back-End Install
            command: |
              npm run backend:install
        - run:
            name: Front-End Build
            command: |
              npm run frontend:build
            filters:
              branches:
                only: master
        - run:
            name: Back-End Build
            command: |
              npm run backend:build
            filters:
              branches:
                only: master
        - run:
            name: Deploy App Frontend
            command: |
              npm run frontend:deploy
        - run:
            name: Deploy App Backend
            command: |
              npm run backend:deploy
            filters:
              branches:
                only: master
